### PR TITLE
feat: find vaulted files automatically for `config-diff`

### PR DESCRIPTION
**Pull request by jackhodgkiss**
Remove the need to manage `KAYOBE_CONFIG_VAULTED_FILES_PATHS_EXTRA` which can be annoying having to update this as new vaulted files get added.

### CODE REVIEW

**Comment by Alex-Welsh** [comment]
One general comment, have you considered/tested how this interacts with symlinks? I'm just wondering if you could end up with duplicates in your list

**Comment by jackhodgkiss** [comment]
> One general comment, have you considered/tested how this interacts with symlinks? I'm just wondering if you could end up with duplicates in your list

Will investigated.

**Comment by jackhodgkiss** [comment]
> One general comment, have you considered/tested how this interacts with symlinks? I'm just wondering if you could end up with duplicates in your list

I think this handled by `redact_config_dir` and `encrypt_config_dir` which uses realpath to expand paths and also checks for unique files.

https://github.com/stackhpc/kayobe-automation/blob/main/scripts/config-diff.sh#L107

**Review by Alex-Welsh — APPROVED** [review]
lgtm

**Review by jovial — APPROVED** [review]
Looks good to me

**Pull request merged**
